# Netlify configuration file

# Handle application form redirects
[[redirects]]
  from = "/qualification-form"
  to = "/application-form"
  status = 301
  force = true

# Handle questionnaire redirects (legacy path)
[[redirects]]
  from = "/questionnaire"
  to = "/application-form"
  status = 301
  force = true

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"